apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webchat
  template:
    metadata:
      name: webchat
      labels:
        app: frontend
    spec:
      containers:
        - name: webchat
          image: gauravdemo06/myapp:v1
          ports:
            - containerPort: 80
